schema: "./schemas/*.graphql"
documents: "./schemas/query.*.graphql"
extensions:
  codegen:
    generates:
      ./server/src/types/schemas.generated.ts:
        hooks:
          afterOneFileWrite:
            - prettier --write
        plugins:
          - typescript
          - typescript-resolvers
      ./server/src/graphql/schema.generated.graphql:
          config:
            - includeDirectives: true
          plugins:
            - schema-ast
      ./client/src/graphql/schemas.generated.ts:
        hooks:
          afterOneFileWrite:
            - prettier --write
        plugins:
          - typescript
          - typescript-operations
          - typed-document-node
  # diff:
  #   baseSchema: your-base-schema-here
